version: '3.1'

services:
  front:
    platform: linux/x86_64
    build: .
    container_name: front
    command: dev
    working_dir: /data/app
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 3000:3000
    volumes:
      - ./:/data/app
      - /app/node_modules
    networks:
      - srcnet
    environment:
     - NODE_OPTIONS=--openssl-legacy-provider
networks:
  srcnet:
    driver: bridge